<?php

use Illuminate\Database\Seeder;

class TinTucTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $NoiDung = "
    	</h3>Nội dung tin tức: Khoá học Lập trình PHP tại trung tâm đào tạo tin học khoa phạm</h3>
    	<p>
	    	<b>Hotline kỹ thuật <b>: 0967 908 907 <br>
	    	<b>Hotline tư vấn kháo học <b>: 094 276 4080 <br>
	    	<b>Địa chỉ </b>: 90 Lê Thị Riêng, P.Bến Thành, Q1, TPHCM <br>
	    	<b>Website</b>: khoapham.vn <br>
	    	<b>Học Online tại :</b>online.khoapham.vn <br>
    	</p>
    	";

        DB::table('tintucs')->insert([
        	/*['TieuDe' => 'Lần đầu ĐH FPT cấp học bổng tiến sĩ ','TieuDeKhongDau' => 'Lan-Dau-Dh-Fpt-Cap-Hoc-Bong-Tien-Si','TomTat' => 'Bên cạnh 400 suất học bổng Nguyễn Văn Đạo, ĐH FPT lần đầu tiên chọn ra 30 học sinh xuất sắc nhất để cấp học bổng toàn phần đào tạo từ cử nhân lên thẳng tiến sĩ, với tổng giá trị quỹ lên tới 5 triệu USD.','NoiDung' => $NoiDung,'Hinh' => 'FPT-2.jpg','NoiBat' => 1, 'idLoaiTin'=>'1', 'created_at' => new DateTime(), 'updated_at' => new DateTime()],
            ['TieuDe' => '300 tỷ đồng phát triển giáo dục mầm non ','TieuDeKhongDau' => '300-Ty-Dong-Phat-Trien-Giao-Duc-Mam-Non','TomTat' => 'Bộ Giáo dục và Đào tạo đang xây dựng chương trình, mục tiêu quốc gia về giáo dục giai đoạn 2011-2015, trong đó dự kiến chi 300 tỷ đồng để phát triển giáo dục mầm non năm 2011. ','NoiDung' => $NoiDung,'Hinh' => 'tre_em_set_sub.jpg','NoiBat' => 1, 'idLoaiTin'=>'1', 'created_at' => new DateTime(), 'updated_at' => new DateTime()],
            ['TieuDe' => 'Nợ giáo viên tiền tỷ chi phí phổ cập giáo dục ','TieuDeKhongDau' => 'No-Giao-Vien-Tien-Ty-Chi-Phi-Pho-Cap-Giao-Duc','TomTat' => 'Ba năm qua, nhiều giáo viên ở Khánh Hòa bỏ công sức, kể cả tiền bạc để thực hiện phổ cập giáo dục cho học sinh trên địa bàn tỉnh, song đến nay vẫn chưa nhận được tiền chính quyền chi trả. ','NoiDung' => $NoiDung,'Hinh' => 'pho-cap-giao-duc-nho-2.jpg','NoiBat' => 1,'idLoaiTin'=>'1', 'created_at' => new DateTime(), 'updated_at' => new DateTime()],
            ['TieuDe' => 'Những nụ hôn ngọt ngào trong đêm tình nhân ','TieuDeKhongDau' => 'Nhung-Nu-Hon-Ngot-Ngao-Trong-Dem-Tinh-Nhan','TomTat' => 'Tối 13/2, hàng nghìn bạn trẻ có mặt tại cầu Ánh Sao (quận 7, TP HCM) chứng kiến những lời tỏ tình cùng những nụ hôn ngọt ngào của 100 cặp tình nhân trong "Đêm Valentine thế kỷ". ','NoiDung' => $NoiDung,'Hinh' => '250h_jpg_thumb210x0_ns.jpg','NoiBat' => 1,'idLoaiTin'=>'2', 'created_at' => new DateTime(), 'updated_at' => new DateTime()],
            ['TieuDe' => 'Hot girl tâm sự về ngày Valentine ','TieuDeKhongDau' => 'Hot-Girl-Tam-Su-Ve-Ngay-Valentine','TomTat' => 'Một bông hồng trắng bằng khăn giấy, chiếc xe đạp gắn đầy hoa, hay bài thơ của chàng "thi sĩ" vô danh gửi tặng… là những món quà đầy ấn tượng mà hot girl Midu từng nhận được trong các mùa Valentine. ','NoiDung' => $NoiDung,'Hinh' => 'hot-girl-valentine-2.jpg','NoiBat' => 1,'idLoaiTin'=>'2', 'created_at' => new DateTime(), 'updated_at' => new DateTime()],*/

            ['TieuDe' => 'Đón và chăm sóc trẻ sau giờ tan trường qua dịch vụ ','TieuDeKhongDau' => 'Don-Va-Cham-Soc-Tre-Sau-Gio-Tan-Truong-Qua-Dich-Vu','TomTat' => 'Các bé sẽ được chăm sóc bữa ăn, tắm rửa sạch sẽ, vui chơi và học tập cùng cô giáo theo các nội dung trong sổ báo bài, mở rộng hoặc đào sâu kiến thức theo yêu cầu của phụ huynh. ','NoiDung' => $NoiDung,'Hinh' => 'be-2.jpg','NoiBat' => 1,'idLoaiTin'=>'1', 'created_at' => new DateTime(), 'updated_at' => new DateTime()],
            ['TieuDe' => '7 học sinh rơi từ tầng hai xuống đất vì gãy lan can ','TieuDeKhongDau' => '7-Hoc-Sinh-Roi-Tu-Tang-Hai-Xuong-Dat-Vi-Gay-Lan-Can','TomTat' => 'Đang giờ ra chơi, bất ngờ toàn bộ lan can tầng hai của Trường THCS thị trấn Chợ Rã (Bắc Kạn) gãy đổ ra ngoài, kéo theo 7 học sinh lớp 6A rơi xuống đất. ','NoiDung' => $NoiDung,'Hinh' => 'tai_nan_set_top.gif','NoiBat' => 1,'idLoaiTin'=>'1', 'created_at' => new DateTime(), 'updated_at' => new DateTime()],
            ['TieuDe' => 'Giáo viên TP HCM được thưởng tết tối thiểu 700.000 đồng ','TieuDeKhongDau' => 'Giao-Vien-Tp-Hcm-Duoc-Thuong-Tet-Toi-Thieu-700.000-Dong','TomTat' => 'Sở GD&ĐT TP HCM vừa có thông báo về việc UBND thành phố chấp thuận đề nghị hỗ trợ mức quà tết cho cán bộ công chức trong ngành tối thiểu là 700.000 đồng. Mức thưởng này cao hơn năm ngoái 100.000 đồng. ','NoiDung' => $NoiDung,'Hinh' => 'thuong-tet-3.jpg','NoiBat' => 1,'idLoaiTin'=>'1', 'created_at' => new DateTime(), 'updated_at' => new DateTime()],
            ['TieuDe' => 'Mức sinh hoạt phí tối đa cho lưu học sinh là 1.200 USD ','TieuDeKhongDau' => 'Muc-Sinh-Hoat-Phi-Toi-Da-Cho-Luu-Hoc-Sinh-La-1.200-Usd','TomTat' => 'Đối với lưu học sinh tại Ba Lan, Bungary, Nga..., mức sinh hoạt phí sẽ tăng từ 400 USD lên 480 USD; tại Australia, New Zealand tăng từ 860 USD lên 1.032 USD và tại Mỹ, Canada, Anh, Nhật Bản tăng từ 1.000 lên 1.200 USD một người một tháng... ','NoiDung' => $NoiDung,'Hinh' => 'du_hoc_sinh_set_sub.jpg','NoiBat' => 1,'idLoaiTin'=>'1', 'created_at' => new DateTime(), 'updated_at' => new DateTime()],
            ['TieuDe' => 'Học sinh Hà Nội được nghỉ 11 ngày Tết ','TieuDeKhongDau' => 'Hoc-Sinh-Ha-Noi-Duoc-Nghi-11-Ngay-Tet','TomTat' => 'UBND thành phố Hà Nội vừa đồng ý với đề xuất của Sở Giáo dục và Đào tạo về việc cho học sinh nghỉ tết Tết Nguyên đán Tân Mão 11 ngày. ','NoiDung' => $NoiDung,'Hinh' => 't2.jpg','NoiBat' => 1,'idLoaiTin'=>'1', 'created_at' => new DateTime(), 'updated_at' => new DateTime()],
            ['TieuDe' => 'Hàng trăm nghìn học sinh nghỉ học vì giá rét ','TieuDeKhongDau' => 'Hang-Tram-Nghin-Hoc-Sinh-Nghi-Hoc-Vi-Gia-Ret','TomTat' => 'Sớm nay, các trường tiểu học ở Hà Nội đều trưng biển thông báo nghỉ học do nhiệt độ ở mức 8 độ C. Một vài phụ huynh không theo dõi dự báo thời tiết vẫn đưa con đến trường và ngậm ngùi quay xe ra về. ','NoiDung' => $NoiDung,'Hinh' => 'phu_huynh_xem_lich_nghi_hoc_set_sub.jpg','NoiBat' => 1,'idLoaiTin'=>'1', 'created_at' => new DateTime(), 'updated_at' => new DateTime()],
            ['TieuDe' => 'Phương pháp Mathnasium giúp trẻ yêu thích môn toán ','TieuDeKhongDau' => 'Phuong-Phap-Mathnasium-Giup-Tre-Yeu-Thich-Mon-Toan','TomTat' => 'Phương pháp dạy toán Mathnasium với 5 kỹ thuật giảng dạy bổ sung nhau, giúp trẻ em tiếp thu kiến thức toán hiệu quả, không cảm thấy áp lực và nhàm chán. ','NoiDung' => $NoiDung,'Hinh' => 'hinh_250x195[1]_JPG_thumb210x0_ns.jpg','NoiBat' => 1,'idLoaiTin'=>'1', 'created_at' => new DateTime(), 'updated_at' => new DateTime()],

            ['TieuDe' => 'Một mình ở Thái Lan ','TieuDeKhongDau' => 'Mot-Minh-O-Thai-Lan','TomTat' => 'Không quá ồn ã tấp nập như Hong Kong, hay quá yên bình như Hội An, Bangkok khiến cho tôi cảm thấy vô cùng phấn khích, tựa hồ như vừa thức giấc sau một cơn ngủ say. Bạn Nguyễn Anh Ngọc viết. ','NoiDung' => $NoiDung,'Hinh' => 'top1.jpg','NoiBat' => 1,'idLoaiTin'=>'3', 'created_at' => new DateTime(), 'updated_at' => new DateTime()],
            ['TieuDe' => 'Trai Hà thành trổ tài vật cầu đầu xuân','TieuDeKhongDau' => 'Trai-Ha-Thanh-Tro-Tai-Vat-Cau-Dau-Xuan','TomTat' => 'Những pha tranh cướp quyết liệt cùng những tiếng cười vui là hình ảnh về lễ hội vật cầu đầu xuân của các thanh niên làng Thúy Lĩnh, quận Hoàng Mai (Hà Nội), diễn ra chiều 8/2 (6 Tết). ','NoiDung' => $NoiDung,'Hinh' => '130.jpg','NoiBat' => 1,'idLoaiTin'=>'3', 'created_at' => new DateTime(), 'updated_at' => new DateTime()],
            ['TieuDe' => 'Các bãi biển Đà Nẵng đồng loạt thả chim bồ câu ','TieuDeKhongDau' => 'Cac-Bai-Bien-Da-Nang-Dong-Loat-Tha-Chim-Bo-Cau','TomTat' => 'Sáng nay, Ban quản lý bán đảo Sơn Trà và các bãi biển du lịch thành phố Đà Nẵng đã tổ chức thả chim bồ câu, phát động xây dựng vườn chim hòa bình tại công viên biển Đông. ','NoiDung' => $NoiDung,'Hinh' => 'thachim2.jpg','NoiBat' => 1,'idLoaiTin'=>'3', 'created_at' => new DateTime(), 'updated_at' => new DateTime()],
            ['TieuDe' => 'Đi tìm cây đa đại thụ hơn nghìn năm tuổi ','TieuDeKhongDau' => 'Di-Tim-Cay-Da-Dai-Thu-Hon-Nghin-Nam-Tuoi','TomTat' => 'Chúng tôi thẳng tiến về Bán đảo Sơn Trà (Đà Nẵng) nơi được mạnh danh là “Mắt thần Đông Dương”. Mục tiêu của chúng tôi là khám phá cây đa cổ thụ hơn nghìn năm tuổi. Đường dốc và ngoằn nghèo khiến du khách có cảm giác như bay lên thiên giới. Bạn Triệu Hòa chia sẻ. ','NoiDung' => $NoiDung,'Hinh' => 'cayda2.jpg','NoiBat' => 1,'idLoaiTin'=>'3', 'created_at' => new DateTime(), 'updated_at' => new DateTime()],
            ['TieuDe' => 'Rêu nảy lộc xuân trên phố cổ Hội An','TieuDeKhongDau' => 'Reu-Nay-Loc-Xuan-Tren-Pho-Co-Hoi-An','TomTat' => 'Trong màn sương lãng đãng, phố cổ Hội An hiện ra như bức tranh bình dị mà sâu lắng. Rêu nảy lộc trên từng ngõ phố, bật mầm trên từng mái ngói cũ xưa gieo nhớ thương, neo lòng du khách trong khoảnh khắc mùa xuân đang về. ','NoiDung' => $NoiDung,'Hinh' => 'a-top-2-reu-xuan-HA.jpg','NoiBat' => 1,'idLoaiTin'=>'3', 'created_at' => new DateTime(), 'updated_at' => new DateTime()],
            ['TieuDe' => 'Du học hè Singapore 2011','TieuDeKhongDau' => 'Du-Hoc-He-Singapore-2011','TomTat' => 'Đăng ký trước ngày 29/1, học sinh sẽ được tặng 6 triệu đồng khi tham gia lịch trình 4 tuần ở tại resort và tặng 4 triệu đồng cho học sinh tham gia lịch trình 2 hoặc 3 tuần ở tại resort.','NoiDung' => $NoiDung,'Hinh' => '400.jpg','NoiBat' => 1,'idLoaiTin'=>'4', 'created_at' => new DateTime(), 'updated_at' => new DateTime()],
            ['TieuDe' => 'Chương trình trung học tại Canada','TieuDeKhongDau' => 'Chuong-Trinh-Trung-Hoc-Tai-Canada','TomTat' => 'Bà Birgit Hartel, Giám đốc tuyển sinh nhóm các trường công lập River East Transcona, tỉnh Manitoba, Canada sẽ giới thiệu về môi trường sống và học tập từ 18h đến 20h ngày 21/1 tại số 22 phố Phạm Huy Thông, Ba Đình, Hà Nội.','NoiDung' => $NoiDung,'Hinh' => 'New-Image250.jpg','NoiBat' => 1,'idLoaiTin'=>'4', 'created_at' => new DateTime(), 'updated_at' => new DateTime()],
            ['TieuDe' => 'Ngành quản trị khách sạn và du lịch tại Thụy Sĩ','TieuDeKhongDau' => 'Nganh-Quan-Tri-Khach-San-Va-Du-Lich-Tai-Thuy-Si','TomTat' => 'G’Connect Education tổ chức buổi giới thiệu thông tin du học Thụy Sĩ với đại diện trường Quản lý khách sạn IHTTI vào từ 17h30 đến 20h30 ngày 24/2 tại khách sạn Sheraton, 88 Đồng Khởi, quận 1, TP HCM (Hanoi Room, tầng 2)','NoiDung' => $NoiDung,'Hinh' => 'Festival-17_Ve-tranh.jpg','NoiBat' => 1,'idLoaiTin'=>'4', 'created_at' => new DateTime(), 'updated_at' => new DateTime()],
            ['TieuDe' => 'Du học tại Queen Mary và London Metropolitan (Anh)','TieuDeKhongDau' => 'Du-Hoc-Tai-Queen-Mary-Va-London-Metropolitan--Anh-','TomTat' => 'Đại diện trường Queen Mary và London Metropolitan sẽ tham gia hội thảo tuyển sinh được tổ chức tại Hà Nội và TP HCM.','NoiDung' => $NoiDung,'Hinh' => 'sunrise-1.jpg','NoiBat' => 1,'idLoaiTin'=>'4', 'created_at' => new DateTime(), 'updated_at' => new DateTime()],
            ['TieuDe' => 'Các trường Nhật ngữ tuyển sinh','TieuDeKhongDau' => 'Cac-Truong-Nhat-Ngu-Tuyen-Sinh','TomTat' => 'Đại diện tuyển sinh của các trường Nhật ngữ tổ chức phỏng vấn và nhận hồ sơ trực tiếp từ học sinh có nguyện vọng du học Nhật Bản cho kỳ khai giảng tháng 7 tại Trung tâm thương mại và hợp tác quốc tế UDIC, Hà Nội.','NoiDung' => $NoiDung,'Hinh' => 'toi1.jpg','NoiBat' => 1,'idLoaiTin'=>'4', 'created_at' => new DateTime(), 'updated_at' => new DateTime()],
            ['TieuDe' => 'Vợ đánh hổ cứu chồng','TieuDeKhongDau' => 'Vo-Danh-Ho-Cuu-Chong','TomTat' => 'Một phụ nữ ở phía bắc Malaysia đánh hổ bằng muỗng gỗ khi con thú tấn công chồng bà, nhờ đó người đàn ông thoát chết.','NoiDung' => $NoiDung,'Hinh' => 'tiger.jpg','NoiBat' => 1,'idLoaiTin'=>'5', 'created_at' => new DateTime(), 'updated_at' => new DateTime()],

            ['TieuDe' => 'Nga đưa tên lửa tối tân lên đảo tranh chấp với Nhật','TieuDeKhongDau' => 'Nga-Dua-Ten-Lua-Toi-Tan-Len-Dao-Tranh-Chap-Voi-Nhat','TomTat' => 'Matxcơva sẽ triển khai hệ thống tên lửa phòng không hiện đại tầm ngắn và trung lên các đảo tranh chấp với Nhật Bản, quan chức cấp cao của Bộ Tổng tham mưu Nga cho biết hôm nay.','NoiDung' => $NoiDung,'Hinh' => 's400.jpg','NoiBat' => 1,'idLoaiTin'=>'5', 'created_at' => new DateTime(), 'updated_at' => new DateTime()],
            ['TieuDe' => 'Mỹ - Hàn sắp tập trận khổng lồ','TieuDeKhongDau' => 'My---Han-Sap-Tap-Tran-Khong-Lo','TomTat' => 'Mỹ và Hàn Quốc sẽ tổ chức một cuộc diễn tập chung vào tháng này, cho dù căng thẳng với Triều Tiên vẫn kéo dài sau vụ đụng độ gần biên giới vào năm ngoái.','NoiDung' => $NoiDung,'Hinh' => 'carrier.jpg','NoiBat' => 1,'idLoaiTin'=>'5', 'created_at' => new DateTime(), 'updated_at' => new DateTime()],
            ['TieuDe' => 'Đánh bom tự sát ở Nga','TieuDeKhongDau' => 'Danh-Bom-Tu-Sat-O-Nga','TomTat' => 'Hai cảnh sát thiệt mạng và hơn 20 người bị thương trong hai vụ đánh bom tự sát ở nước Cộng hòa Dagestan thuộc vùng Bắc Kavkaz của Nga.','NoiDung' => $NoiDung,'Hinh' => 'x1.jpg','NoiBat' => 1,'idLoaiTin'=>'5', 'created_at' => new DateTime(), 'updated_at' => new DateTime()],
            ['TieuDe' => 'Trung Quốc ủng hộ đại tướng trẻ của Triều Tiên','TieuDeKhongDau' => 'Trung-Quoc-Ung-Ho-Dai-Tuong-Tre-Cua-Trieu-Tien','TomTat' => 'Một quan chức cấp cao của Trung Quốc bày tỏ sự ủng hộ đối với kế hoạch chuyển giao quyền lực của Chủ tịch Triều Tiên Kim Jong-il cho con trai út, hãng thông tấn chính thức của Triều Tiên cho hay.','NoiDung' => $NoiDung,'Hinh' => 'jong-un.jpg','NoiBat' => 1,'idLoaiTin'=>'5', 'created_at' => new DateTime(), 'updated_at' => new DateTime()],
             ['TieuDe' => 'Làn sóng biểu tình khắp thế giới Ảrập','TieuDeKhongDau' => 'Lan-Song-Bieu-Tinh-Khap-The-Gioi-Arap','TomTat' => 'Cuộc lật đổ chế độ của người dân Ai Cập gây ra hiệu ứng domino trên toàn thế giới Ảrập, khi người dân các nước trong khu vực liên tiếp đổ ra đường đòi hạ bệ chính phủ.','NoiDung' => $NoiDung,'Hinh' => 'arap1.jpg','NoiBat' => 1,'idLoaiTin'=>'5', 'created_at' => new DateTime(), 'updated_at' => new DateTime()],
            ['TieuDe' => 'Tập trận Hổ mang Vàng 2011','TieuDeKhongDau' => 'Tap-Tran-Ho-Mang-Vang-2011','TomTat' => 'Cuộc tập trận trên bộ lớn nhất thế giới năm nay nhằm đánh dấu 30 năm ra đời sự kiện, trong đó tập trung vào huấn luyện kỹ năng quân sự cơ bản, lên kế hoạch nhân sự và các dự án hỗ trợ nhân đạo.','NoiDung' => $NoiDung,'Hinh' => 'gold1.jpg','NoiBat' => 1,'idLoaiTin'=>'6', 'created_at' => new DateTime(), 'updated_at' => new DateTime()],
            ['TieuDe' => 'Ai Cập trở lại cuộc sống thường nhật','TieuDeKhongDau' => 'Ai-Cap-Tro-Lai-Cuoc-Song-Thuong-Nhat','TomTat' => 'Các hàng quán mở cửa trở lại, công sở, nhà băng đi vào hoạt động, đường phố vắng vẻ yên tĩnh. Nhịp sống Ai Cập dần trở lại như trước khi có hàng loạt cuộc biểu tình rầm rộ kéo dài.','NoiDung' => $NoiDung,'Hinh' => 'bt1.jpg','NoiBat' => 1,'idLoaiTin'=>'6', 'created_at' => new DateTime(), 'updated_at' => new DateTime()],
            ['TieuDe' => 'Ảnh báo chí thế giới 2010','TieuDeKhongDau' => 'Anh-Bao-Chi-The-Gioi-2010','TomTat' => 'Chân dung của cô gái Afghanistan 18 tuổi Bibi Aisha bị chồng là một chiến binh Taliban cắt mất mũi đoạt giải Ảnh báo chí thế giới của năm 2010.','NoiDung' => $NoiDung,'Hinh' => 'p1.jpg','NoiBat' => 1,'idLoaiTin'=>'6', 'created_at' => new DateTime(), 'updated_at' => new DateTime()],
            ['TieuDe' => 'Lễ tình nhân trên khắp thế giới','TieuDeKhongDau' => 'Le-Tinh-Nhan-Tren-Khap-The-Gioi','TomTat' => 'Không khí ngày lễ tình yêu Valentine tưng bừng, nhộn nhịp, trên khắp các con phố từ Trung Quốc, Nhật Bản, cho tới New York, Mexico. ','NoiDung' => $NoiDung,'Hinh' => 'va10.jpg','NoiBat' => 1,'idLoaiTin'=>'6', 'created_at' => new DateTime(), 'updated_at' => new DateTime()],
            ['TieuDe' => 'Thưởng thơ xuân ở Berlin','TieuDeKhongDau' => 'Thuong-Tho-Xuan-O-Berlin','TomTat' => 'Lúc nhận được lời mời đi tham dự đêm Thơ Nguyên tiêu, do câu lạc bộ người yêu thơ Berlin tổ chức, tôi cứ mãi ngập ngừng. Thành thật mà nói, tình yêu thơ thì tôi có thật, nhưng hôm ấy lại là một đêm mùa đông khá lạnh.','NoiDung' => $NoiDung,'Hinh' => 'tho1.jpg','NoiBat' => 1,'idLoaiTin'=>'6', 'created_at' => new DateTime(), 'updated_at' => new DateTime()],
            ['TieuDe' => 'Tôi đi đào vàng ở Australia','TieuDeKhongDau' => 'Toi-Di-Dao-Vang-O-Australia','TomTat' => 'Chúng tôi dựng lều ở khu cắm trại trong một công viên quốc gia cách nơi chúng tôi ở khoảng vài giờ lái xe. Hằng ngày hai đứa tôi mang máy dò vàng đi rà dọc theo những con suối cạn nước trong rừng.','NoiDung' => $NoiDung,'Hinh' => 'nn.jpg','NoiBat' => 1,'idLoaiTin'=>'7', 'created_at' => new DateTime(), 'updated_at' => new DateTime()],
            ['TieuDe' => 'Thủy thủ trên tàu Việt Nam ở Ấn Độ kêu cứu','TieuDeKhongDau' => 'Thuy-Thu-Tren-Tau-Viet-Nam-O-An-Do-Keu-Cuu','TomTat' => '"Chúng tôi không còn gì để ăn. 85% đồ đạc trên tàu đều hỏng hết. Công ty không còn cung cấp thực phẩm. Xin hãy cứu chúng tôi".','NoiDung' => $NoiDung,'Hinh' => 'c1.jpg','NoiBat' => 1,'idLoaiTin'=>'7', 'created_at' => new DateTime(), 'updated_at' => new DateTime()],
            ['TieuDe' => 'Tiệm hoa ở Little Saigon rộn ràng ngày Tình yêu','TieuDeKhongDau' => 'Tiem-Hoa-O-Little-Saigon-Ron-Rang-Ngay-Tinh-Yeu','TomTat' => 'Các tiệm hoa ở Little Saigon, quận Cam, California, tấp nập người mua bán trong ngày Tình yêu sáng qua.','NoiDung' => $NoiDung,'Hinh' => 'valentine3.jpg','NoiBat' => 1,'idLoaiTin'=>'7', 'created_at' => new DateTime(), 'updated_at' => new DateTime()],
            ['TieuDe' => 'Nên ở lại Mỹ hay về Việt Nam?','TieuDeKhongDau' => 'Nen-O-Lai-My-Hay-Ve-Viet-Nam-','TomTat' => 'Tôi không xinh, và với tuổi tác hiện nay, tôi sợ không biết liệu về Việt Nam có thể có tìm được cho mình một hạnh phúc riêng hay không.','NoiDung' => $NoiDung,'Hinh' => 'tt1_1.jpg','NoiBat' => 1,'idLoaiTin'=>'7', 'created_at' => new DateTime(), 'updated_at' => new DateTime()],
             ['TieuDe' => 'Internet châm ngòi lật đổ Mubarak như thế nào','TieuDeKhongDau' => 'Internet-Cham-Ngoi-Lat-Do-Mubarak-Nhu-The-Nao','TomTat' => 'Những người Ai Cập trẻ tuổi phát động cuộc biểu tình từ ngày 25/1 qua các trang mạng xã hội. Chính quyền lập tức ngăn chặn nhưng vô hiệu và sau 18 ngày người dân nổi dậy, Tổng thống Mubarak buộc phải "nhổ neo".','NoiDung' => $NoiDung,'Hinh' => 'Ghonim.jpg','NoiBat' => 1,'idLoaiTin'=>'8', 'created_at' => new DateTime(), 'updated_at' => new DateTime()],
            ['TieuDe' => 'Tình hình Iran nguy cơ theo bước Ai Cập','TieuDeKhongDau' => 'Tinh-Hinh-Iran-Nguy-Co-Theo-Buoc-Ai-Cap','TomTat' => 'Sau Tunisia và Ai Cập, làn sóng biểu tình đang lan khắp Trung Đông, đặc biệt tại nước không thuộc thế giới Ảrập là Iran, vốn đang bị Mỹ can thiệp trực tiếp bằng cách công khai ủng hộ người biểu tình.','NoiDung' => $NoiDung,'Hinh' => 'Tehran.jpg','NoiBat' => 1,'idLoaiTin'=>'8', 'created_at' => new DateTime(), 'updated_at' => new DateTime()],
            ['TieuDe' => 'Trung Đông vui buồn lẫn lộn vì Mubarak từ chức','TieuDeKhongDau' => 'Trung-Dong-Vui-Buon-Lan-Lon-Vi-Mubarak-Tu-Chuc','TomTat' => 'Trung Đông vui buồn lẫn lộn vì Mubarak từ chức Hàng trăm nghìn người dân ở khu vực Trung Đông đổ ra đường phố để ăn mừng sau khi Tổng thống Ai Cập Hosni Mubarak từ chức hôm qua, trong khi nhiều người dân Israel tỏ ra lo ngại cho tương lai của họ.','NoiDung' => $NoiDung,'Hinh' => 'cam4.jpg','NoiBat' => 1,'idLoaiTin'=>'8', 'created_at' => new DateTime(), 'updated_at' => new DateTime()],
            ['TieuDe' => 'Hàn Quốc tranh cãi về việc đánh học sinh','TieuDeKhongDau' => 'Han-Quoc-Tranh-Cai-Ve-Viec-Danh-Hoc-Sinh','TomTat' => 'Năm học mới càng đến gần, cô giáo trung học Jennifer Chung càng lo lắng khi sắp phải xa người bạn đồng hành lâu năm của mình - chiếc roi cô thường dùng để trị những học sinh ngỗ ngược.','NoiDung' => $NoiDung,'Hinh' => 'han2.jpg','NoiBat' => 1,'idLoaiTin'=>'8', 'created_at' => new DateTime(), 'updated_at' => new DateTime()],
            ['TieuDe' => 'Chiến lược quốc phòng Mỹ tập trung vào châu Á','TieuDeKhongDau' => 'Chien-Luoc-Quoc-Phong-My-Tap-Trung-Vao-Chau-A','TomTat' => 'Lầu Năm Góc tuyên bố sẽ tiếp tục xây dựng đồng minh và tập trung giải quyết xung đột bằng cách triển khai thêm lực lượng ở các khu vực nhiều đe dọa, đặc biệt là châu Á và Thái Bình Dương.','NoiDung' => $NoiDung,'Hinh' => 'm1.jpg','NoiBat' => 1,'idLoaiTin'=>'8', 'created_at' => new DateTime(), 'updated_at' => new DateTime()],
            ['TieuDe' => 'Đảo chiều giữa phiên, Vn-Index giảm gần 5 điểm','TieuDeKhongDau' => 'Dao-Chieu-Giua-Phien,-Vn-Index-Giam-Gan-5-Diem','TomTat' => 'Giao dịch trên thị trường chứng khoán tiếp tục lình xình khi các cổ phiếu lớn không chứng tỏ vai trò dẫn dắt. Vn-Index và HNX-Index đồng loạt giảm khoảng 1%.','NoiDung' => $NoiDung,'Hinh' => 'chung-khoan-0.jpg','NoiBat' => 1,'idLoaiTin'=>'9', 'created_at' => new DateTime(), 'updated_at' => new DateTime()],
            ['TieuDe' => 'Vn-Index mất điểm phiên thứ 3 liên tiếp','TieuDeKhongDau' => 'Vn-Index-Mat-Diem-Phien-Thu-3-Lien-Tiep','TomTat' => 'Xu hướng điều chỉnh của thị trường chứng khoán tiếp tục nối dài trong phiên giao dịch sáng nay khi các chỉ số đồng loạt giảm điểm. Tuy nhiên, lực cầu bắt đáy có dấu hiệu tăng cao, đặc biệt là trên sàn Hà Nội.','NoiDung' => $NoiDung,'Hinh' => 'chung-khoan-0 (1).jpg','NoiBat' => 1,'idLoaiTin'=>'9', 'created_at' => new DateTime(), 'updated_at' => new DateTime()],
            ['TieuDe' => 'Đầu năm, chứng khoán khởi động chậm','TieuDeKhongDau' => 'Dau-Nam,-Chung-Khoan-Khoi-Dong-Cham','TomTat' => 'Trong tuần giao dịch đầu tiên của năm Tân Mão, khối lượng cổ phiếu được chuyển nhượng trên 2 sàn Hà Nội và TP HCM đồng loạt giảm khoảng 7%. Index tuy vẫn tăng nhưng chủ yếu dựa vào lực đẩy từ các cổ phiếu lớn.','NoiDung' => $NoiDung,'Hinh' => 'chung-khoan-0 (2).jpg','NoiBat' => 1,'idLoaiTin'=>'9', 'created_at' => new DateTime(), 'updated_at' => new DateTime()],
            ['TieuDe' => 'Xem xét xây dựng chỉ số phụ cho 2 sàn chứng khoán','TieuDeKhongDau' => 'Xem-Xet-Xay-Dung-Chi-So-Phu-Cho-2-San-Chung-Khoan','TomTat' => 'Ủy ban Chứng khoán Nhà nước (SSC) vừa có văn bản yêu cầu 2 Sở giao dịch chứng khoán Hà Nội và TP HCM tìm biện pháp khắc phục tình trạng "méo mó" của Index do tác động từ các cổ phiếu có vốn hóa lớn trên thị trường.','NoiDung' => $NoiDung,'Hinh' => 'chung-khoan-0_1.jpg','NoiBat' => 1,'idLoaiTin'=>'9', 'created_at' => new DateTime(), 'updated_at' => new DateTime()],
            ['TieuDe' => 'Sóng’ blue-chip','TieuDeKhongDau' => 'Song’-Blue-Chip','TomTat' => 'Trong nhiều phiên giao dịch gần đây, một số cổ phiếu lớn như BVH, MSN, HAG, CTG… tăng giá rất mạnh đẩy Vn-Index từ 480 điểm vượt 520 điểm. Những blue-chip đang tạo ra "sóng" trên thị trường.','NoiDung' => $NoiDung,'Hinh' => 'song-bluechip.jpg','NoiBat' => 1,'idLoaiTin'=>'9', 'created_at' => new DateTime(), 'updated_at' => new DateTime()],
            ['TieuDe' => 'Chung cư mini đầu tiên ở TP HCM rao bán','TieuDeKhongDau' => 'Chung-Cu-Mini-Dau-Tien-O-Tp-Hcm-Rao-Ban','TomTat' => 'Ngày 15/2, Công ty TNHH Tổ hợp Vina và Công ty Địa ốc Hoàng Anh Sài Gòn bắt đầu bán 19 căn hộ của tòa nhà Vinacomplex III gây xôn xao giới buôn địa ốc. Bởi lẽ, đây là loại hình chung cư mini đầu tiên tại TP HCM.','NoiDung' => $NoiDung,'Hinh' => 'a-tb-chung-cu-mini.jpg','NoiBat' => 1,'idLoaiTin'=>'10', 'created_at' => new DateTime(), 'updated_at' => new DateTime()],
            ['TieuDe' => 'Đề xuất sở hữu chung cư có thời hạn gây nhiều tranh cãi','TieuDeKhongDau' => 'De-Xuat-So-Huu-Chung-Cu-Co-Thoi-Han-Gay-Nhieu-Tranh-Cai','TomTat' => 'Bộ Xây dựng cho rằng, sở hữu nhà chung cư có thời hạn sẽ thuận tiện cho việc nâng cấp, cải tạo đồng thời làm giảm giá chung cư. Tuy nhiên, nhiều ý kiến lo ngại, người dân có thể bị sốc và quay lưng lại với mô hình này.','NoiDung' => $NoiDung,'Hinh' => 'chung1.jpg','NoiBat' => 1,'idLoaiTin'=>'10', 'created_at' => new DateTime(), 'updated_at' => new DateTime()],
            ['TieuDe' => 'Thép và xi măng cùng tăng giá','TieuDeKhongDau' => 'Thep-Va-Xi-Mang-Cung-Tang-Gia','TomTat' => 'Từ đầu tháng đến nay, nhiều doanh nghiệp thép đã tăng giá từ 200.000 đồng đến 500.000 đồng mỗi tấn. Xi măng cũng tăng 60.000 đồng. Theo dự báo, hai mặt hàng này sẽ còn biến động nếu điện và than đồng loạt tăng giá.','NoiDung' => $NoiDung,'Hinh' => 'thep_1.jpg','NoiBat' => 1,'idLoaiTin'=>'10', 'created_at' => new DateTime(), 'updated_at' => new DateTime()],
            ['TieuDe' => 'Kinh Bắc sẽ khởi công dự án tỷ đô trong quý I','TieuDeKhongDau' => 'Kinh-Bac-Se-Khoi-Cong-Du-An-Ty-Do-Trong-Quy-I','TomTat' => 'Trao đổi với VnExpress.net, ông Đặng Thành Tâm, Chủ tịch Tập đoàn Kinh Bắc cho hay, chủ đầu tư đã được chấp thuận khởi công dự án tòa nhà phức hợp 100 tầng có tên Lotus trong quý I.','NoiDung' => $NoiDung,'Hinh' => 'kb1.jpg','NoiBat' => 1,'idLoaiTin'=>'10', 'created_at' => new DateTime(), 'updated_at' => new DateTime()],
            ['TieuDe' => 'Thành phố ven sông Hồng sẽ hạn chế nhà cao tầng','TieuDeKhongDau' => 'Thanh-Pho-Ven-Song-Hong-Se-Han-Che-Nha-Cao-Tang','TomTat' => 'Phó giám đốc Sở Quy hoạch Kiến trúc Hà Nội Dương Đức Tuấn cho hay, sau khi lồng ghép vào quy hoạch chung thủ đô, dự án thành phố ven sông Hồng sẽ hạn chế, giảm bớt các nhà cao tầng để phát triển không gian xanh.','NoiDung' => $NoiDung,'Hinh' => 'dan.jpg','NoiBat' => 1,'idLoaiTin'=>'10', 'created_at' => new DateTime(), 'updated_at' => new DateTime()],

    	]);
    }
}
